# Netlify configuration file
# This file controls how Netlify builds and deploys your site

[build]
  # Directory to change to before starting a build
  base = "/"
  
  # Directory that contains the deploy-ready HTML files and assets
  publish = "/"
  
  # Default build command (not needed for static sites)
  # command = "npm run build"

[build.environment]
  # Environment variables for build (if needed)
  NODE_VERSION = "18"

# Redirect rules (optional)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    
[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000"
    
[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000"
    
[[headers]]
  for = "*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"